# Generated by Django 3.1.3 on 2020-12-17 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0007_auto_20201217_2254'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResultPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.match')),
            ],
        ),
    ]
