# Generated by Django 3.1.3 on 2021-03-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('U', 'User Post'), ('B', 'Called Bet Post'), ('M', 'Match Result Post')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='CalledBetPost',
        ),
    ]
