# Generated by Django 3.1.3 on 2021-02-06 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_auto_20210206_1845'),
        ('feed', '0003_auto_20210206_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalledBetPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.calledbet')),
                ('sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.sticker')),
            ],
        ),
    ]
