# Generated by Django 3.1.3 on 2021-04-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0011_auto_20210404_0008'),
        ('feed', '0003_auto_20210306_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='called_bet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.calledbet'),
        ),
    ]
