# Generated by Django 3.1.3 on 2021-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('U', 'User Post'), ('B', 'Called Bet Post')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='MatchResultPost',
        ),
    ]
