# Generated by Django 3.1.3 on 2021-02-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20210206_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
