# Generated by Django 3.1.3 on 2021-02-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
