# Generated by Django 3.1.3 on 2021-02-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20210207_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.sticker'),
        ),
    ]
