# Generated by Django 3.1.3 on 2021-05-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.accesscode'),
        ),
    ]
