# Generated by Django 3.1.3 on 2021-05-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.accesscode'),
        ),
    ]
