# Generated by Django 3.1.3 on 2021-02-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('position', models.IntegerField()),
                ('band', models.CharField(choices=[('T', 'Top'), ('M', 'Middle'), ('B', 'Bottom')], max_length=1)),
            ],
        ),
    ]
