# Generated by Django 3.1.3 on 2020-12-06 12:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_accesscode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(default=users.models.generate_random_code, max_length=10),
        ),
    ]
