# Generated by Django 3.1.3 on 2020-11-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMatchBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country_code', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(default=-1)),
                ('ko_time', models.DateTimeField()),
                ('result', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_away_team', to='enter.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='enter.team')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F')], max_length=1)),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_team_1', to='enter.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_team_2', to='enter.team')),
                ('team_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_team_3', to='enter.team')),
                ('team_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_team_4', to='enter.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_winner', to='enter.team')),
            ],
        ),
    ]
