# Generated by Django 3.1.3 on 2020-12-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country_code', models.CharField(default='', max_length=3)),
                ('flag', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F')], max_length=1)),
                ('goals_scored', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('ko_time', models.DateTimeField()),
                ('result', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('goals_scored', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('own_goals', models.IntegerField(default=0)),
                ('hatricks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FinalMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enter.match')),
                ('first_goal_period', models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('1E', 'First Half of Extra Time'), ('2E', 'Second Half of Extra Time'), ('PS', 'Penality Shootout')], max_length=2)),
                ('has_own_goal', models.BooleanField(default=False)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('ref_nationality', models.CharField(choices=[('EU', 'European'), ('SA', 'South American'), ('OT', 'Other Continent')], max_length=2)),
            ],
            bases=('enter.match',),
        ),
        migrations.CreateModel(
            name='GroupMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enter.match')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.group')),
            ],
            bases=('enter.match',),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('seconds_to_first_yellow', models.IntegerField()),
                ('seconds_to_first_goal', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.country')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.group')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('goals_scored', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_away_team', to='enter.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='enter.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.venue'),
        ),
        migrations.CreateModel(
            name='GroupMatchBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.groupmatch')),
            ],
        ),
    ]
