# Generated by Django 3.1.3 on 2021-02-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='CalledBet',
        ),
    ]
