# Generated by Django 3.1.3 on 2020-12-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('enter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalmatch',
            old_name='ref_nationality',
            new_name='ref_continent',
        ),
        migrations.AddField(
            model_name='groupmatchbet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='seconds_to_first_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='seconds_to_first_yellow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
