# Generated by Django 3.1.3 on 2020-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_auto_20201201_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='seconds_to_first_goal',
            field=models.IntegerField(default=5400),
        ),
        migrations.AlterField(
            model_name='team',
            name='seconds_to_first_yellow',
            field=models.IntegerField(default=5400),
        ),
    ]
