# Generated by Django 3.1.3 on 2021-02-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_auto_20210206_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('when_called', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='outcome',
            name='choice_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.choicegroup'),
        ),
    ]
