# Generated by Django 3.1.3 on 2021-03-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_auto_20210228_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
