# Generated by Django 3.1.3 on 2021-03-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0003_gamecategory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecategory',
            options={'verbose_name_plural': 'game categories'},
        ),
    ]
