# Generated by Django 3.1.3 on 2021-02-11 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0003_auto_20210208_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='position',
            new_name='current_position',
        ),
        migrations.CreateModel(
            name='PositionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('called_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.calledbet')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
    ]
