# Generated by Django 3.1.3 on 2020-12-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201202_0948'),
        ('enter', '0003_auto_20201201_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='finalmatch',
            options={'verbose_name_plural': 'final matches'},
        ),
        migrations.AlterModelOptions(
            name='groupmatch',
            options={'verbose_name_plural': 'group matches'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.RenameField(
            model_name='finalmatch',
            old_name='has_own_goal',
            new_name='own_goal',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='flags_and_logos'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(upload_to='flags_and_logos'),
        ),
        migrations.AlterField(
            model_name='groupmatchbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
