# Generated by Django 3.1.3 on 2020-12-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_auto_20201202_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmatchbet',
            name='user',
        ),
    ]
