# Generated by Django 3.1.3 on 2021-03-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_auto_20210306_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiftyfiftyquestion',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
