# Generated by Django 3.1.3 on 2021-02-11 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_auto_20210211_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('score', models.IntegerField()),
                ('called_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.calledbet')),
            ],
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='score',
            new_name='current_score',
        ),
        migrations.DeleteModel(
            name='PositionLog',
        ),
        migrations.AddField(
            model_name='entrystatelog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry'),
        ),
    ]
