# Generated by Django 3.1.3 on 2021-02-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0005_auto_20210211_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('called_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.calledbet')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('called_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.calledbet')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
        migrations.DeleteModel(
            name='EntryStateLog',
        ),
    ]
