# Generated by Django 3.1.3 on 2021-03-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0005_fiftyfiftyquestion_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgoalsoutcome',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamenthattricksoutcome',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentowngoalsoutcome',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentredcardsoutcome',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
