# Generated by Django 3.1.3 on 2020-12-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201206_1252'),
        ('enter', '0005_remove_groupmatchbet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FM', 'Group Matches'), ('GW', 'Group Winners'), ('TG', 'Top Goalscoring Group'), ('TP', 'Top Goalscoring Player'), ('TS', 'Best Teams Success'), ('FF', '50/50s'), ('TC', 'Tournament Multiple Choice'), ('FC', 'Final Multiple Choice')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_submitted', models.DateTimeField()),
                ('has_paid', models.BooleanField(default=False)),
                ('has_submitted', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FiftyFiftyOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_a', models.CharField(max_length=100)),
                ('choice_b', models.CharField(max_length=100)),
                ('winning_amount_a', models.IntegerField()),
                ('winning_amount_b', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='groupmatchbet',
            name='match',
        ),
        migrations.CreateModel(
            name='ToWinOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRedCardsOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_red_cards_range', models.IntegerField()),
                ('max_red_cards_range', models.IntegerField()),
                ('winning_amount', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentOwnGoalsOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_own_goals_range', models.IntegerField()),
                ('max_own_goals_range', models.IntegerField()),
                ('winning_amount', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentHatricksOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hatricks_range', models.IntegerField()),
                ('max_hatricks_range', models.IntegerField()),
                ('winning_amount', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentGoalsOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_goals_range', models.IntegerField()),
                ('max_goals_range', models.IntegerField()),
                ('winning_amount', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
                ('total_goals_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentgoalsoutcome')),
                ('total_hattricks_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamenthatricksoutcome')),
                ('total_own_goals_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentowngoalsoutcome')),
                ('total_red_cards_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentredcardsoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='ToReachSemiFinalOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='ToReachFinalOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='TopGoalScoringPlayerOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.player')),
            ],
        ),
        migrations.CreateModel(
            name='TopGoalscoringPlayerBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringplayeroutcome')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
        migrations.CreateModel(
            name='TopGoalScoringGroupOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.group')),
            ],
        ),
        migrations.CreateModel(
            name='TopGoalscoringGroupBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringgroupoutcome')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
        migrations.CreateModel(
            name='MostYellowCardsOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='HighestScoringTeamOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='GroupWinnerOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='GroupWinnerBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.groupwinneroutcome')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMatchOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1)),
                ('winning_amount', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.groupmatch')),
            ],
        ),
        migrations.CreateModel(
            name='FinalYellowCardsOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow_cards', models.IntegerField()),
                ('winning_amount', models.IntegerField()),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalmatch')),
            ],
        ),
        migrations.CreateModel(
            name='FinalRefContinentOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_goal_period', models.CharField(choices=[('EU', 'European'), ('SA', 'South American'), ('OT', 'Other Continent')], max_length=2)),
                ('winning_amount', models.IntegerField()),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalmatch')),
            ],
        ),
        migrations.CreateModel(
            name='FinalOwnGoalOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_goal', models.BooleanField()),
                ('winning_amount', models.IntegerField()),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalmatch')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGoalsOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('winning_amount', models.IntegerField()),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalmatch')),
            ],
        ),
        migrations.CreateModel(
            name='FinalFirstGoalOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_goal_period', models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('1E', 'First Half of Extra Time'), ('2E', 'Second Half of Extra Time'), ('PS', 'Penality Shootout')], max_length=2)),
                ('winning_amount', models.IntegerField()),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalmatch')),
            ],
        ),
        migrations.CreateModel(
            name='FinalBetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
                ('final_first_goal_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalfirstgoaloutcome')),
                ('final_goals_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalgoalsoutcome')),
                ('final_own_goals_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalowngoaloutcome')),
                ('final_ref_continent_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalrefcontinentoutcome')),
                ('final_yellow_cards_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalyellowcardsoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='FiftyFiftyBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.fiftyfiftyoutcome')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
        migrations.CreateModel(
            name='FastestYellowCardsOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='FastestGoalOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
        ),
        migrations.CreateModel(
            name='BestTeamsSuccessBetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
                ('fastest_tournament_goal_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.fastestgoaloutcome')),
                ('fastest_yellow_card_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.fastestyellowcardsoutcome')),
                ('highest_scoring_team_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.highestscoringteamoutcome')),
                ('most_yellow_cards_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.mostyellowcardsoutcome')),
                ('to_reach_final_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.toreachfinaloutcome')),
                ('to_reach_semi_final_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.toreachsemifinaloutcome')),
                ('to_win_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.towinoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='groupmatchbet',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enter.entry'),
        ),
        migrations.AlterField(
            model_name='groupmatchbet',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.groupmatchoutcome'),
        ),
    ]
