# Generated by Django 3.1.3 on 2020-12-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0006_auto_20201213_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('A', 'Away'), ('D', 'Draw')], max_length=1),
        ),
    ]
