# Generated by Django 3.1.3 on 2021-03-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0006_auto_20210311_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgoalsoutcome',
            name='is_highest_value',
        ),
        migrations.RemoveField(
            model_name='tournamenthattricksoutcome',
            name='is_highest_value',
        ),
        migrations.RemoveField(
            model_name='tournamentowngoalsoutcome',
            name='is_highest_value',
        ),
        migrations.RemoveField(
            model_name='tournamentredcardsoutcome',
            name='is_highest_value',
        ),
        migrations.AlterField(
            model_name='tournamentgoalsoutcome',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentgoalsoutcome',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamenthattricksoutcome',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamenthattricksoutcome',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentowngoalsoutcome',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentowngoalsoutcome',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentredcardsoutcome',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentredcardsoutcome',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
