# Generated by Django 3.1.3 on 2021-02-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0006_auto_20210212_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionlog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_logs', to='enter.entry'),
        ),
        migrations.AlterField(
            model_name='scorelog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='enter.entry'),
        ),
    ]
