# Generated by Django 3.1.3 on 2020-12-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0007_auto_20201217_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmatchoutcome',
            old_name='result',
            new_name='outcome',
        ),
    ]
