# Generated by Django 3.1.3 on 2020-12-21 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0008_auto_20201220_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
