# Generated by Django 3.1.3 on 2021-02-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0008_auto_20210217_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='label',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
