# Generated by Django 3.1.3 on 2021-04-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0009_auto_20210312_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='calledbet',
            name='num_correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calledbet',
            name='num_incorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
