# Generated by Django 3.1.3 on 2020-12-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0009_auto_20201221_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentHatricksOutcome',
            new_name='TournamentHattricksOutcome',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RenameField(
            model_name='tournamenthattricksoutcome',
            old_name='max_hatricks_range',
            new_name='max_hattricks_range',
        ),
        migrations.RenameField(
            model_name='tournamenthattricksoutcome',
            old_name='min_hatricks_range',
            new_name='min_hattricks_range',
        ),
    ]
