# Generated by Django 3.1.3 on 2021-02-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0009_entry_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='called_bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.calledbet'),
        ),
    ]
