# Generated by Django 3.1.3 on 2020-12-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0010_auto_20201223_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentgoalsoutcome',
            old_name='max_goals_range',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='tournamentgoalsoutcome',
            old_name='min_goals_range',
            new_name='min_value',
        ),
        migrations.RenameField(
            model_name='tournamenthattricksoutcome',
            old_name='max_hattricks_range',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='tournamenthattricksoutcome',
            old_name='min_hattricks_range',
            new_name='min_value',
        ),
        migrations.RenameField(
            model_name='tournamentowngoalsoutcome',
            old_name='max_own_goals_range',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='tournamentowngoalsoutcome',
            old_name='min_own_goals_range',
            new_name='min_value',
        ),
        migrations.RenameField(
            model_name='tournamentredcardsoutcome',
            old_name='max_red_cards_range',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='tournamentredcardsoutcome',
            old_name='min_red_cards_range',
            new_name='min_value',
        ),
    ]
