# Generated by Django 3.1.3 on 2021-04-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0010_auto_20210403_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calledbet',
            name='num_correct',
        ),
        migrations.RemoveField(
            model_name='calledbet',
            name='num_incorrect',
        ),
        migrations.CreateModel(
            name='CalledBetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correct', models.IntegerField(blank=True, null=True)),
                ('num_incorrect', models.IntegerField(blank=True, null=True)),
                ('called_bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.calledbet')),
            ],
        ),
    ]
