# Generated by Django 3.1.3 on 2020-12-24 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0011_auto_20201223_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentbetgroup',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.entry'),
        ),
    ]
