# Generated by Django 3.1.3 on 2021-04-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0011_auto_20210404_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='correct_bets',
            field=models.IntegerField(default=0),
        ),
    ]
