# Generated by Django 3.1.3 on 2020-12-28 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0012_auto_20201224_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmatch',
            name='first_goal_period',
            field=models.CharField(blank=True, choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('1E', 'First Half of Extra Time'), ('2E', 'Second Half of Extra Time'), ('PS', 'Penality Shootout')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='goals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='ref_continent',
            field=models.CharField(blank=True, choices=[('EU', 'European'), ('SA', 'South American'), ('OT', 'Other Continent')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='yellow_cards',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_away_team', to='enter.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='enter.team'),
        ),
    ]
