# Generated by Django 3.1.3 on 2021-05-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0013_entry_current_team_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiftyfiftyquestion',
            name='brief_question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
