# Generated by Django 3.1.3 on 2020-12-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0013_auto_20201228_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalfirstgoaloutcome',
            old_name='first_goal_period',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='finalgoalsoutcome',
            old_name='goals',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='finalowngoaloutcome',
            old_name='own_goal',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='finalrefcontinentoutcome',
            old_name='first_goal_period',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='finalyellowcardsoutcome',
            old_name='yellow_cards',
            new_name='outcome',
        ),
    ]
