# Generated by Django 3.1.3 on 2020-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0014_auto_20201228_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgoalsoutcome',
            name='is_highest_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamenthattricksoutcome',
            name='is_highest_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentowngoalsoutcome',
            name='is_highest_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentredcardsoutcome',
            name='is_highest_value',
            field=models.BooleanField(default=False),
        ),
    ]
