# Generated by Django 3.1.3 on 2021-05-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0014_fiftyfiftyquestion_brief_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
