# Generated by Django 3.1.3 on 2020-12-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0015_auto_20201228_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalgoalsoutcome',
            old_name='outcome',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='finalyellowcardsoutcome',
            old_name='outcome',
            new_name='max_value',
        ),
        migrations.AddField(
            model_name='finalgoalsoutcome',
            name='is_highest_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finalgoalsoutcome',
            name='min_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finalyellowcardsoutcome',
            name='is_highest_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finalyellowcardsoutcome',
            name='min_value',
            field=models.IntegerField(default=0),
        ),
    ]
