# Generated by Django 3.1.3 on 2021-05-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('enter', '0015_auto_20210509_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentHattricksOutcome',
            new_name='TournamentGoalsInAGameOutcome',
        ),
        migrations.RenameModel(
            old_name='TournamentRedCardsOutcome',
            new_name='TournamentPenaltiesOutcome',
        ),
    ]
