# Generated by Django 3.1.3 on 2020-12-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0016_auto_20201228_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgoalsoutcome',
            name='min_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finalyellowcardsoutcome',
            name='min_value',
            field=models.IntegerField(),
        ),
    ]
