# Generated by Django 3.1.3 on 2021-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0016_auto_20210509_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='goals_scored',
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
