# Generated by Django 3.1.3 on 2021-05-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0017_auto_20210509_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostCleanSheetsOutcome',
            fields=[
                ('outcome_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enter.outcome')),
                ('team', models.ForeignKey(limit_choices_to={'is_top_team': True}, on_delete=django.db.models.deletion.CASCADE, to='enter.team')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('enter.outcome',),
        ),
    ]
