# Generated by Django 3.1.3 on 2021-05-09 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0018_mostcleansheetsoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRefCountryOutcome',
            fields=[
                ('outcome_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enter.outcome')),
                ('choice', models.CharField(choices=[('ENG', 'English'), ('ESP', 'Spanish'), ('ITA', 'Italian'), ('GER', 'German'), ('OTH', 'Other')], max_length=3)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('enter.outcome',),
        ),
        migrations.RemoveField(
            model_name='finalrefcontinentoutcome',
            name='final',
        ),
        migrations.RemoveField(
            model_name='finalrefcontinentoutcome',
            name='outcome_ptr',
        ),
        migrations.RemoveField(
            model_name='finalmatch',
            name='ref_continent',
        ),
        migrations.DeleteModel(
            name='FinalOwnGoalOutcome',
        ),
        migrations.DeleteModel(
            name='FinalRefContinentOutcome',
        ),
        migrations.AddField(
            model_name='finalrefcountryoutcome',
            name='final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.finalmatch'),
        ),
    ]
