# Generated by Django 3.1.3 on 2020-12-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0019_auto_20201229_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestteamssuccessbetgroup',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.entry'),
        ),
        migrations.AlterField(
            model_name='finalbetgroup',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.entry'),
        ),
    ]
