# Generated by Django 3.1.3 on 2021-05-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0019_auto_20210509_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmatch',
            name='ref_country',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('ESP', 'Spanish'), ('ITA', 'Italian'), ('GER', 'German'), ('OTH', 'Other')], max_length=3, null=True),
        ),
    ]
