# Generated by Django 3.1.3 on 2020-12-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0020_auto_20201229_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiftyFiftyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='fiftyfiftyoutcome',
            old_name='winning_amount_a',
            new_name='winning_amount',
        ),
        migrations.RemoveField(
            model_name='fiftyfiftyoutcome',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='fiftyfiftyoutcome',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='fiftyfiftyoutcome',
            name='winning_amount_b',
        ),
        migrations.AddField(
            model_name='fiftyfiftyoutcome',
            name='outcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiftyfiftyoutcome',
            name='fifty_fifty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enter.fiftyfiftyquestion'),
        ),
    ]
