# Generated by Django 3.1.3 on 2021-05-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0020_finalmatch_ref_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalfirstgoaloutcome',
            name='choice',
            field=models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('1E', 'First Half of ET'), ('2E', 'Second Half of ET'), ('PS', 'Penalty Shootout')], max_length=2),
        ),
        migrations.AlterField(
            model_name='finalmatch',
            name='first_goal_period',
            field=models.CharField(blank=True, choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('1E', 'First Half of ET'), ('2E', 'Second Half of ET'), ('PS', 'Penalty Shootout')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='choice_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.choicegroup'),
        ),
    ]
