# Generated by Django 3.1.3 on 2020-12-30 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0021_auto_20201230_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiftyfiftyoutcome',
            name='fifty_fifty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.fiftyfiftyquestion'),
        ),
        migrations.AlterField(
            model_name='fiftyfiftyoutcome',
            name='outcome',
            field=models.BooleanField(),
        ),
    ]
