# Generated by Django 3.1.3 on 2020-12-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0022_auto_20201230_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topgoalscoringplayerbet',
            old_name='bet',
            new_name='player_bet',
        ),
    ]
