# Generated by Django 3.1.3 on 2021-05-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0022_auto_20210512_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='when_called',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
