# Generated by Django 3.1.3 on 2021-05-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0023_bet_when_called'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='when_called',
            new_name='updated_on',
        ),
    ]
