# Generated by Django 3.1.3 on 2021-01-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0024_auto_20210104_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
