# Generated by Django 3.1.3 on 2021-01-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0025_entry_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMatchBetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
                ('match10_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match10outcome_set', to='enter.groupmatchoutcome')),
                ('match11_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match11outcome_set', to='enter.groupmatchoutcome')),
                ('match12_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match12outcome_set', to='enter.groupmatchoutcome')),
                ('match13_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match13outcome_set', to='enter.groupmatchoutcome')),
                ('match14_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match14outcome_set', to='enter.groupmatchoutcome')),
                ('match15_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match15outcome_set', to='enter.groupmatchoutcome')),
                ('match16_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match16outcome_set', to='enter.groupmatchoutcome')),
                ('match17_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match17outcome_set', to='enter.groupmatchoutcome')),
                ('match18_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match18outcome_set', to='enter.groupmatchoutcome')),
                ('match19_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match19outcome_set', to='enter.groupmatchoutcome')),
                ('match1_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1outcome_set', to='enter.groupmatchoutcome')),
                ('match20_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match20outcome_set', to='enter.groupmatchoutcome')),
                ('match21_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match21outcome_set', to='enter.groupmatchoutcome')),
                ('match22_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match22outcome_set', to='enter.groupmatchoutcome')),
                ('match2_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2outcome_set', to='enter.groupmatchoutcome')),
                ('match3_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match3outcome_set', to='enter.groupmatchoutcome')),
                ('match4_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match4outcome_set', to='enter.groupmatchoutcome')),
                ('match5_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match5outcome_set', to='enter.groupmatchoutcome')),
                ('match6_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match6outcome_set', to='enter.groupmatchoutcome')),
                ('match7_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match7outcome_set', to='enter.groupmatchoutcome')),
                ('match8_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match8outcome_set', to='enter.groupmatchoutcome')),
                ('match9_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match9outcome_set', to='enter.groupmatchoutcome')),
            ],
        ),
    ]
