# Generated by Django 3.1.3 on 2021-01-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0026_groupmatchbetgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWinnerBetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
                ('group_A_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupAoutcome_set', to='enter.groupwinneroutcome')),
                ('group_B_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupBoutcome_set', to='enter.groupwinneroutcome')),
                ('group_C_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupCoutcome_set', to='enter.groupwinneroutcome')),
                ('group_D_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupDoutcome_set', to='enter.groupwinneroutcome')),
                ('group_E_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupEoutcome_set', to='enter.groupwinneroutcome')),
                ('group_F_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupFoutcome_set', to='enter.groupwinneroutcome')),
            ],
        ),
    ]
