# Generated by Django 3.1.3 on 2021-01-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0027_groupwinnerbetgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupwinnerbetgroup',
            old_name='group_A_bet',
            new_name='group_a_winner_bet',
        ),
        migrations.RenameField(
            model_name='groupwinnerbetgroup',
            old_name='group_B_bet',
            new_name='group_b_winner_bet',
        ),
        migrations.RenameField(
            model_name='groupwinnerbetgroup',
            old_name='group_C_bet',
            new_name='group_c_winner_bet',
        ),
        migrations.RenameField(
            model_name='groupwinnerbetgroup',
            old_name='group_D_bet',
            new_name='group_d_winner_bet',
        ),
        migrations.RenameField(
            model_name='groupwinnerbetgroup',
            old_name='group_E_bet',
            new_name='group_e_winner_bet',
        ),
        migrations.RenameField(
            model_name='groupwinnerbetgroup',
            old_name='group_F_bet',
            new_name='group_f_winner_bet',
        ),
    ]
