# Generated by Django 3.1.3 on 2021-01-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0028_auto_20210106_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiftyFiftyBetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
                ('question1_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty1outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question2_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty2outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question3_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty3outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question4_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty4outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question5_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty5outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question6_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty6outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question7_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty7outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question8_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty8outcome_set', to='enter.fiftyfiftyoutcome')),
                ('question9_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiftyfifty9outcome_set', to='enter.fiftyfiftyoutcome')),
            ],
        ),
    ]
