# Generated by Django 3.1.3 on 2021-01-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0030_auto_20210106_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmatchbet',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='groupmatchbet',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='groupwinnerbet',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='groupwinnerbet',
            name='entry',
        ),
        migrations.DeleteModel(
            name='FiftyFiftyBet',
        ),
        migrations.DeleteModel(
            name='GroupMatchBet',
        ),
        migrations.DeleteModel(
            name='GroupWinnerBet',
        ),
    ]
