# Generated by Django 3.1.3 on 2021-01-14 23:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0032_entry_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiftyfiftyoutcome',
            old_name='outcome',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='finalfirstgoaloutcome',
            old_name='outcome',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='finalowngoaloutcome',
            old_name='outcome',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='finalrefcontinentoutcome',
            old_name='outcome',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='groupmatchoutcome',
            old_name='outcome',
            new_name='choice',
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastest_goal_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.fastestgoaloutcome')),
                ('fastest_yellow_cards_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.fastestyellowcardsoutcome')),
                ('fifty_fifty_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.fiftyfiftyoutcome')),
                ('final_first_goal_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.finalfirstgoaloutcome')),
                ('final_goals_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.finalgoalsoutcome')),
                ('final_own_goals_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.finalowngoaloutcome')),
                ('final_ref_continent_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.finalrefcontinentoutcome')),
                ('final_yellow_cards_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.finalyellowcardsoutcome')),
                ('group_match_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.groupmatchoutcome')),
                ('group_winner_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.groupwinneroutcome')),
                ('highest_scoring_team_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.highestscoringteamoutcome')),
                ('most_yellow_cards_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.mostyellowcardsoutcome')),
                ('to_reach_final_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.toreachfinaloutcome')),
                ('to_reach_semifinal_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.toreachsemifinaloutcome')),
                ('to_win_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.towinoutcome')),
                ('top_goalscoring_group_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringgroupoutcome')),
                ('top_goalscoring_player_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringplayeroutcome')),
                ('tournament_goals_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentgoalsoutcome')),
                ('tournament_hattricks_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamenthattricksoutcome')),
                ('tournament_own_goals_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentowngoalsoutcome')),
                ('tournament_red_cards_outcome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentredcardsoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.outcome')),
            ],
        ),
    ]
