# Generated by Django 3.1.3 on 2021-01-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0033_auto_20210114_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='fastest_goal_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.fastestgoaloutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='fastest_yellow_cards_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.fastestyellowcardsoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='fifty_fifty_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.fiftyfiftyoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='final_first_goal_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.finalfirstgoaloutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='final_goals_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.finalgoalsoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='final_own_goals_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.finalowngoaloutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='final_ref_continent_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.finalrefcontinentoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='final_yellow_cards_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.finalyellowcardsoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='group_match_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.groupmatchoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='group_winner_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.groupwinneroutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='highest_scoring_team_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.highestscoringteamoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='most_yellow_cards_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.mostyellowcardsoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='to_reach_final_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.toreachfinaloutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='to_reach_semifinal_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.toreachsemifinaloutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='to_win_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.towinoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='top_goalscoring_group_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringgroupoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='top_goalscoring_player_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringplayeroutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='tournament_goals_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentgoalsoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='tournament_hattricks_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.tournamenthattricksoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='tournament_own_goals_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentowngoalsoutcome'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='tournament_red_cards_outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enter.tournamentredcardsoutcome'),
        ),
    ]
