# Generated by Django 3.1.3 on 2021-01-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0034_auto_20210114_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bets',
        ),
        migrations.RenameField(
            model_name='topgoalscoringgroupbet',
            old_name='bet',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='topgoalscoringplayerbet',
            old_name='player_bet',
            new_name='choice',
        ),
    ]
