# Generated by Django 3.1.3 on 2021-01-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0035_auto_20210119_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='topgoalscoringgroupbet',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topgoalscoringplayerbet',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
