# Generated by Django 3.1.3 on 2021-01-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0036_auto_20210119_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topgoalscoringgroupbet',
            name='number',
        ),
        migrations.RemoveField(
            model_name='topgoalscoringplayerbet',
            name='number',
        ),
    ]
