# Generated by Django 3.1.3 on 2021-01-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0037_auto_20210119_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topgoalscoringgroupbet',
            old_name='choice',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='topgoalscoringplayerbet',
            old_name='choice',
            new_name='outcome',
        ),
    ]
