# Generated by Django 3.1.3 on 2021-01-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0039_auto_20210119_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topgoalscoringgroupbet',
            old_name='choice',
            new_name='group_choice',
        ),
    ]
