# Generated by Django 3.1.3 on 2021-02-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0040_auto_20210119_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
            ],
        ),
        migrations.RemoveField(
            model_name='topgoalscoringgroupbet',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='topgoalscoringgroupbet',
            name='group_choice',
        ),
        migrations.RemoveField(
            model_name='topgoalscoringplayerbet',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='topgoalscoringplayerbet',
            name='entry',
        ),
        migrations.CreateModel(
            name='GroupWinnerBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enter.bet')),
                ('group_winner_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.groupwinneroutcome')),
            ],
            bases=('enter.bet',),
        ),
        migrations.DeleteModel(
            name='GroupWinnerBetGroup',
        ),
        migrations.DeleteModel(
            name='TopGoalscoringGroupBet',
        ),
        migrations.DeleteModel(
            name='TopGoalscoringPlayerBet',
        ),
    ]
