# Generated by Django 3.1.3 on 2021-02-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0041_auto_20210203_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGoalscoringPlayerBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enter.bet')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringplayeroutcome')),
            ],
            bases=('enter.bet',),
        ),
        migrations.CreateModel(
            name='TopGoalscoringGroupBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enter.bet')),
                ('group_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.topgoalscoringgroupoutcome')),
            ],
            bases=('enter.bet',),
        ),
    ]
