# Generated by Django 3.1.3 on 2021-02-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0043_auto_20210205_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='winning_amount',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.entry')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enter.outcome')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='bets',
            field=models.ManyToManyField(through='enter.Bet', to='enter.Outcome'),
        ),
    ]
